development:
  adapter: postgresql
  database: qjp
  host: localhost

test:
  adapter: postgresql
  database: qjp_test
  host: localhost

production:
  adapter: postgresql
  database: qjp
  host: localhost